v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
T {100nA} -1100 -540 0 0 0.4 0.4 {}
T {Each bias_nstack is a 50nA unit current sink, and each bias_pstack is a 50nA unit current source.
Any bias current back-end can be generated by chaining together unit sources and/or sinks.} -1360 -630 0 0 0.4 0.4 {}
T {100nA} -1120 -30 0 0 0.4 0.4 {}
T {1uA} -710 -540 0 0 0.4 0.4 {}
T {600nA} -190 -530 0 0 0.4 0.4 {}
T {400nA} 200 -530 0 0 0.4 0.4 {}
T {200nA} 580 -530 0 0 0.4 0.4 {}
T {200nA} 960 -530 0 0 0.4 0.4 {}
T {200nA} 1330 -530 0 0 0.4 0.4 {}
T {100nA} 1700 -530 0 0 0.4 0.4 {}
T {50nA} 2070 -530 0 0 0.4 0.4 {}
T {Level shifters (1.8V to 3.3V)} -2140 -660 0 0 0.4 0.4 {}
T {Bias generator back-end} -2190 -780 0 0 0.6 0.6 {}
T {(Specific back-end used for Chipalooza test chip)} -2190 -730 0 0 0.5 0.5 {}
N -950 -120 -950 -60 {
lab=avss}
N -950 -200 -950 -160 {
lab=snk_test1}
N -1210 -450 -1210 -400 {
lab=pbias}
N -1240 -380 -1210 -380 {
lab=pcasc}
N -910 -490 -910 -400 {
lab=avdd}
N -910 -320 -910 -280 {
lab=src_test1}
N -1210 -360 -1210 -300 {
lab=enb_test1_3v3}
N -840 -450 -840 -400 {
lab=pbias}
N -870 -380 -840 -380 {
lab=pcasc}
N -870 -470 -870 -380 {
lab=pcasc}
N -540 -490 -540 -400 {
lab=avdd}
N -540 -320 -540 -280 {
lab=src_1000}
N -840 -360 -840 -300 {
lab=enb_1000_3v3}
N -300 -450 -300 -400 {
lab=pbias}
N -330 -380 -300 -380 {
lab=pcasc}
N -330 -470 -330 -380 {
lab=pcasc}
N 0 -490 0 -400 {
lab=avdd}
N 0 -320 0 -280 {
lab=src_600}
N -300 -360 -300 -300 {
lab=enb_600_3v3}
N -440 -490 480 -490 {
lab=avdd}
N -440 -470 480 -470 {
lab=pcasc}
N -440 -450 480 -450 {
lab=pbias}
N 90 -450 90 -400 {
lab=pbias}
N 60 -380 90 -380 {
lab=pcasc}
N 60 -470 60 -380 {
lab=pcasc}
N 390 -490 390 -400 {
lab=avdd}
N 390 -320 390 -280 {
lab=src_400}
N 90 -360 90 -300 {
lab=enb_400_3v3}
N 470 -450 470 -400 {
lab=pbias}
N 440 -380 470 -380 {
lab=pcasc}
N 440 -470 440 -380 {
lab=pcasc}
N 770 -490 770 -400 {
lab=avdd}
N 470 -360 470 -300 {
lab=enb_200_0_3v3}
N 480 -450 1400 -450 {
lab=pbias}
N 480 -470 1390 -470 {
lab=pcasc}
N 480 -490 1390 -490 {
lab=avdd}
N 850 -450 850 -400 {
lab=pbias}
N 820 -380 850 -380 {
lab=pcasc}
N 820 -470 820 -380 {
lab=pcasc}
N 1150 -490 1150 -400 {
lab=avdd}
N 1150 -320 1150 -280 {
lab=src_200_1}
N 850 -360 850 -300 {
lab=enb_200_1_3v3}
N 1220 -450 1220 -400 {
lab=pbias}
N 1190 -380 1220 -380 {
lab=pcasc}
N 1190 -470 1190 -380 {
lab=pcasc}
N 1520 -490 1520 -400 {
lab=avdd}
N 1520 -320 1520 -280 {
lab=src_200_2}
N 1220 -360 1220 -300 {
lab=enb_200_2_3v3}
N 1390 -490 2140 -490 {
lab=avdd}
N 1590 -450 1590 -400 {
lab=pbias}
N 1560 -380 1590 -380 {
lab=pcasc}
N 1560 -470 1560 -380 {
lab=pcasc}
N 1890 -490 1890 -400 {
lab=avdd}
N 1890 -320 1890 -280 {
lab=src_100}
N 1590 -360 1590 -300 {
lab=enb_100_3v3}
N 1960 -450 1960 -400 {
lab=pbias}
N 1930 -380 1960 -380 {
lab=pcasc}
N 1930 -470 1930 -380 {
lab=pcasc}
N 2260 -490 2260 -400 {
lab=avdd}
N 2260 -320 2260 -280 {
lab=src_50}
N 1960 -360 1960 -300 {
lab=enb_50_3v3}
N 2140 -490 2260 -490 {
lab=avdd}
N 1390 -470 1930 -470 {
lab=pcasc}
N 1400 -450 1960 -450 {
lab=pbias}
N 770 -320 770 -290 {
lab=src_200_0}
N -910 -340 -890 -340 {
lab=avss}
N -890 -340 -890 -250 {
lab=avss}
N -930 -250 -890 -250 {
lab=avss}
N -930 -250 -930 -60 {
lab=avss}
N -540 -340 -520 -340 {
lab=avss}
N -520 -340 -520 -250 {
lab=avss}
N -560 -250 -520 -250 {
lab=avss}
N -560 -250 -560 -60 {
lab=avss}
N 0 -340 30 -340 {
lab=avss}
N 30 -340 30 -240 {
lab=avss}
N -80 -240 30 -240 {
lab=avss}
N -80 -240 -80 -60 {
lab=avss}
N 390 -340 410 -340 {
lab=avss}
N 410 -340 410 -250 {
lab=avss}
N 270 -250 410 -250 {
lab=avss}
N 270 -250 270 -60 {
lab=avss}
N 770 -340 800 -340 {
lab=avss}
N 800 -340 800 -60 {
lab=avss}
N 1150 -340 1180 -340 {
lab=avss}
N 1180 -340 1180 -60 {
lab=avss}
N 1520 -340 1550 -340 {
lab=avss}
N 1550 -340 1550 -60 {
lab=avss}
N 1890 -340 1920 -340 {
lab=avss}
N 1920 -340 1920 -60 {
lab=avss}
N 2260 -340 2280 -340 {
lab=avss}
N 2280 -340 2280 -60 {
lab=avss}
N -1940 30 -1880 30 {
lab=ena_snk_test1}
N -1800 30 -1750 30 {
lab=ena_test1_3v3}
N -1940 -550 -1880 -550 {
lab=ena_src_50}
N -1700 -550 -1650 -550 {
lab=enb_50_3v3}
N -1940 -500 -1880 -500 {
lab=ena_src_100}
N -1700 -500 -1650 -500 {
lab=enb_100_3v3}
N -1940 -450 -1880 -450 {
lab=ena_src_200_2}
N -1700 -450 -1650 -450 {
lab=enb_200_2_3v3}
N -1940 -400 -1880 -400 {
lab=ena_src_200_1}
N -1700 -400 -1650 -400 {
lab=enb_200_1_3v3}
N -1940 -350 -1880 -350 {
lab=ena_src_200_0}
N -1700 -350 -1650 -350 {
lab=enb_200_0_3v3}
N -1940 -300 -1880 -300 {
lab=ena_src_400}
N -1700 -300 -1650 -300 {
lab=enb_400_3v3}
N -1940 -250 -1880 -250 {
lab=ena_src_600}
N -1700 -250 -1650 -250 {
lab=enb_600_3v3}
N -1940 -200 -1880 -200 {
lab=ena_src_1000_1}
N -1700 -200 -1650 -200 {
lab=enb_1000_1_3v3}
N -1940 -100 -1880 -100 {
lab=ena_src_test1}
N -1700 -100 -1650 -100 {
lab=enb_test1_3v3}
N -1800 -100 -1780 -100 {
lab=#net1}
N -1800 -200 -1780 -200 {
lab=#net2}
N -1800 -250 -1780 -250 {
lab=#net3}
N -1800 -300 -1780 -300 {
lab=#net4}
N -1800 -350 -1780 -350 {
lab=#net5}
N -1800 -400 -1780 -400 {
lab=#net6}
N -1800 -450 -1780 -450 {
lab=#net7}
N -1800 -500 -1780 -500 {
lab=#net8}
N -1800 -550 -1780 -550 {
lab=#net9}
N -1340 -700 -1300 -700 {
lab=dvdd}
N -1340 -670 -1300 -670 {
lab=dvss}
N -1340 -470 -440 -470 {
lab=pcasc}
N -1340 -450 -1270 -450 {
lab=pbias}
N -1340 -490 -440 -490 {
lab=avdd}
N -1330 -60 -430 -60 {
lab=avss}
N -1240 -470 -1240 -380 {
lab=pcasc}
N -1250 -210 -1250 -160 {
lab=ena_test1_3v3}
N -1330 -140 -1250 -140 {
lab=nbias}
N -1270 -450 -440 -450 {}
N -430 -60 2280 -60 {}
C {devices/iopin.sym} -1330 -60 0 1 {name=p39 lab=avss}
C {devices/iopin.sym} -1340 -490 0 1 {name=p42 lab=avdd}
C {devices/lab_wire.sym} -1270 -450 0 0 {name=p44 sig_type=std_logic lab=pbias}
C {devices/lab_wire.sym} -1270 -470 0 0 {name=p45 sig_type=std_logic lab=pcasc}
C {bias_nstack.sym} -1100 -140 0 0 {name=x18[1:0]}
C {devices/ipin.sym} -1940 30 0 0 {name=p50 lab=ena_snk_test1}
C {devices/iopin.sym} -950 -200 0 1 {name=p51 lab=snk_test1}
C {bias_pstack.sym} -1060 -360 0 0 {name=x16[1:0]}
C {devices/ipin.sym} -1940 -100 0 0 {name=p52 lab=ena_src_test1}
C {devices/iopin.sym} -910 -280 0 1 {name=p53 lab=src_test1}
C {bias_pstack.sym} -690 -360 0 0 {name=x8[19:0]}
C {devices/iopin.sym} -540 -280 0 1 {name=p55 lab=src_1000}
C {devices/ipin.sym} -1940 -200 0 0 {name=p58 lab=ena_src_1000_1}
C {bias_pstack.sym} -150 -360 0 0 {name=x4[11:0]}
C {devices/ipin.sym} -1940 -250 0 0 {name=p64 lab=ena_src_600}
C {devices/iopin.sym} 0 -280 0 1 {name=p65 lab=src_600}
C {bias_pstack.sym} 240 -360 0 0 {name=x5[7:0]}
C {devices/ipin.sym} -1940 -300 0 0 {name=p66 lab=ena_src_400}
C {devices/iopin.sym} 390 -280 0 1 {name=p67 lab=src_400}
C {bias_pstack.sym} 620 -360 0 0 {name=x6[3:0]}
C {devices/ipin.sym} -1940 -350 0 0 {name=p68 lab=ena_src_200_0}
C {devices/iopin.sym} 770 -290 0 1 {name=p69 lab=src_200_0}
C {bias_pstack.sym} 1000 -360 0 0 {name=x7[3:0]}
C {devices/ipin.sym} -1940 -400 0 0 {name=p70 lab=ena_src_200_1}
C {devices/iopin.sym} 1150 -280 0 1 {name=p71 lab=src_200_1}
C {bias_pstack.sym} 1370 -360 0 0 {name=x11[3:0]}
C {devices/ipin.sym} -1940 -450 0 0 {name=p72 lab=ena_src_200_2}
C {devices/iopin.sym} 1520 -280 0 1 {name=p73 lab=src_200_2}
C {bias_pstack.sym} 1740 -360 0 0 {name=x12[1:0]}
C {devices/ipin.sym} -1940 -500 0 0 {name=p74 lab=ena_src_100}
C {devices/iopin.sym} 1890 -280 0 1 {name=p75 lab=src_100}
C {bias_pstack.sym} 2110 -360 0 0 {name=x13}
C {devices/ipin.sym} -1940 -550 0 0 {name=p76 lab=ena_src_50}
C {devices/iopin.sym} 2260 -280 0 1 {name=p77 lab=src_50}
C {devices/lab_pin.sym} -1210 -300 0 1 {name=p11 sig_type=std_logic lab=enb_test1_3v3}
C {devices/lab_pin.sym} -840 -300 0 1 {name=p13 sig_type=std_logic lab=enb_1000_3v3}
C {devices/lab_pin.sym} -300 -300 0 1 {name=p17 sig_type=std_logic lab=enb_600_3v3}
C {devices/lab_pin.sym} -60 -210 0 1 {name=p18 sig_type=std_logic lab=ena_3700_3v3}
C {devices/lab_pin.sym} 90 -300 0 1 {name=p19 sig_type=std_logic lab=enb_400_3v3}
C {devices/lab_pin.sym} 290 -210 0 1 {name=p20 sig_type=std_logic lab=enb_2000_3v3}
C {devices/lab_pin.sym} 470 -300 0 1 {name=p21 sig_type=std_logic lab=enb_200_0_3v3}
C {devices/lab_pin.sym} 850 -300 0 1 {name=p22 sig_type=std_logic lab=enb_200_1_3v3}
C {devices/lab_pin.sym} 1220 -300 0 1 {name=p23 sig_type=std_logic lab=enb_200_2_3v3}
C {devices/lab_pin.sym} 1590 -300 0 1 {name=p24 sig_type=std_logic lab=enb_100_3v3}
C {devices/lab_pin.sym} 1960 -300 0 1 {name=p25 sig_type=std_logic lab=enb_50_3v3}
C {lsbuflv2hv_1.sym} -1840 30 0 0 {name=x10 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {lsbuflv2hv_1.sym} -1840 -550 0 0 {name=x12 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -500 0 0 {name=x14 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -450 0 0 {name=x15 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -400 0 0 {name=x16 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -350 0 0 {name=x17 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -300 0 0 {name=x18 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -250 0 0 {name=x19 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -200 0 0 {name=x20 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -100 0 0 {name=x22 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {devices/lab_pin.sym} -1750 30 0 1 {name=p28 sig_type=std_logic lab=ena_test1_3v3}
C {devices/lab_pin.sym} -1650 -100 0 1 {name=p29 sig_type=std_logic lab=enb_test1_3v3}
C {devices/lab_pin.sym} -1650 -200 0 1 {name=p34 sig_type=std_logic lab=enb_1000_1_3v3}
C {devices/lab_pin.sym} -1650 -250 0 1 {name=p35 sig_type=std_logic lab=enb_600_3v3}
C {devices/lab_pin.sym} -1650 -300 0 1 {name=p37 sig_type=std_logic lab=enb_400_3v3}
C {devices/lab_pin.sym} -1650 -350 0 1 {name=p82 sig_type=std_logic lab=enb_200_0_3v3}
C {devices/lab_pin.sym} -1650 -400 0 1 {name=p83 sig_type=std_logic lab=enb_200_1_3v3}
C {devices/lab_pin.sym} -1650 -450 0 1 {name=p84 sig_type=std_logic lab=enb_200_2_3v3}
C {devices/lab_pin.sym} -1650 -500 0 1 {name=p85 sig_type=std_logic lab=enb_100_3v3}
C {devices/lab_pin.sym} -1650 -550 0 1 {name=p86 sig_type=std_logic lab=enb_50_3v3}
C {sky130_stdcells/inv_2.sym} -1740 -550 0 0 {name=x25 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -500 0 0 {name=x26 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -450 0 0 {name=x27 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -400 0 0 {name=x28 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -350 0 0 {name=x29 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -300 0 0 {name=x30 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -250 0 0 {name=x31 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -200 0 0 {name=x32 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -100 0 0 {name=x34 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {devices/noconn.sym} -910 -360 0 1 {name=l4}
C {devices/noconn.sym} -950 -140 0 1 {name=l5}
C {devices/noconn.sym} -540 -360 0 1 {name=l7}
C {devices/noconn.sym} 0 -360 0 1 {name=l10}
C {devices/noconn.sym} 390 -360 0 1 {name=l13}
C {devices/noconn.sym} 770 -360 0 1 {name=l15}
C {devices/noconn.sym} 1150 -360 0 1 {name=l16}
C {devices/noconn.sym} 1520 -360 0 1 {name=l17}
C {devices/noconn.sym} 1890 -360 0 1 {name=l18}
C {devices/noconn.sym} 2260 -360 0 1 {name=l19}
C {devices/iopin.sym} -1340 -700 0 1 {name=p98 lab=dvdd}
C {devices/iopin.sym} -1340 -670 0 1 {name=p99 lab=dvss}
C {devices/lab_pin.sym} -1300 -700 0 1 {name=p1 sig_type=std_logic lab=dvdd}
C {devices/lab_pin.sym} -1300 -670 0 1 {name=p2 sig_type=std_logic lab=dvss}
C {devices/lab_pin.sym} 1940 -2300 0 0 {name=p109 sig_type=std_logic lab=vbg}
C {devices/ipin.sym} -1340 -470 0 0 {name=p3 lab=pcasc}
C {devices/ipin.sym} -1340 -450 0 0 {name=p4 lab=pbias}
C {devices/ipin.sym} -1330 -140 0 0 {name=p5 lab=nbias}
C {devices/lab_pin.sym} -1250 -210 0 1 {name=p6 sig_type=std_logic lab=ena_test1_3v3}
