v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
T {100nA} -1110 -540 0 0 0.4 0.4 {}
T {Each bias_nstack is a 50nA unit current sink, and each bias_pstack is a 50nA unit current source.
Any bias current back-end can be generated by chaining together unit sources and/or sinks.} -930 -630 0 0 0.4 0.4 {}
T {100nA} -1130 -40 0 0 0.4 0.4 {}
T {1uA} -350 -540 0 0 0.4 0.4 {}
T {10uA} -740 -540 0 0 0.4 0.4 {}
T {5uA} -800 -40 0 0 0.4 0.4 {}
T {750nA} 620 -40 0 0 0.4 0.4 {}
T {600nA} 30 -530 0 0 0.4 0.4 {}
T {400nA} 420 -530 0 0 0.4 0.4 {}
T {200nA} 800 -530 0 0 0.4 0.4 {}
T {200nA} 1180 -530 0 0 0.4 0.4 {}
T {200nA} 1550 -530 0 0 0.4 0.4 {}
T {100nA} 1920 -530 0 0 0.4 0.4 {}
T {50nA} 2290 -530 0 0 0.4 0.4 {}
T {4uA} -440 -40 0 0 0.4 0.4 {}
T {2uA} -60 -40 0 0 0.4 0.4 {}
T {Level shifters (1.8V to 3.3V)} -2140 -660 0 0 0.4 0.4 {}
T {Bias generator back-end} -2190 -780 0 0 0.6 0.6 {}
T {(Specific back-end used for Chipalooza test chip)} -2190 -730 0 0 0.5 0.5 {}
T {1uA} 290 -40 0 0 0.4 0.4 {}
N -960 -120 -960 -60 {
lab=avss}
N -960 -200 -960 -160 {
lab=snk_test1}
N -1220 -450 -1220 -400 {
lab=pbias}
N -1250 -380 -1220 -380 {
lab=pcasc}
N -1250 -470 -1250 -380 {
lab=pcasc}
N -920 -490 -920 -400 {
lab=avdd}
N -920 -320 -920 -280 {
lab=src_test1}
N -1220 -360 -1220 -300 {
lab=enb_test1_3v3}
N -850 -450 -850 -400 {
lab=pbias}
N -880 -380 -850 -380 {
lab=pcasc}
N -880 -470 -880 -380 {
lab=pcasc}
N -550 -490 -550 -400 {
lab=avdd}
N -550 -320 -550 -280 {
lab=src_10000}
N -850 -360 -850 -300 {
lab=enb_10000_3v3}
N -920 -140 -920 -80 {
lab=nbias}
N -620 -120 -620 -60 {
lab=avss}
N -920 -210 -920 -160 {
lab=ena_5000_3v3}
N -620 -200 -620 -160 {
lab=snk_5000}
N -470 -450 -470 -400 {
lab=pbias}
N -500 -380 -470 -380 {
lab=pcasc}
N -500 -470 -500 -380 {
lab=pcasc}
N -170 -490 -170 -400 {
lab=avdd}
N -170 -320 -170 -280 {
lab=src_1000}
N -470 -360 -470 -300 {
lab=enb_1000_3v3}
N 160 -140 160 -80 {
lab=nbias}
N 460 -120 460 -60 {
lab=avss}
N 160 -210 160 -160 {
lab=ena_1000_3v3}
N 460 -200 460 -160 {
lab=snk_1000}
N -80 -450 -80 -400 {
lab=pbias}
N -110 -380 -80 -380 {
lab=pcasc}
N -110 -470 -110 -380 {
lab=pcasc}
N 220 -490 220 -400 {
lab=avdd}
N 220 -320 220 -280 {
lab=src_600}
N -80 -360 -80 -300 {
lab=enb_600_3v3}
N 310 -450 310 -400 {
lab=pbias}
N 280 -380 310 -380 {
lab=pcasc}
N 280 -470 280 -380 {
lab=pcasc}
N 610 -490 610 -400 {
lab=avdd}
N 610 -320 610 -280 {
lab=src_400}
N 310 -360 310 -300 {
lab=enb_400_3v3}
N 690 -450 690 -400 {
lab=pbias}
N 660 -380 690 -380 {
lab=pcasc}
N 660 -470 660 -380 {
lab=pcasc}
N 990 -490 990 -400 {
lab=avdd}
N 690 -360 690 -300 {
lab=enb_200_0_3v3}
N 1070 -450 1070 -400 {
lab=pbias}
N 1040 -380 1070 -380 {
lab=pcasc}
N 1040 -470 1040 -380 {
lab=pcasc}
N 1370 -490 1370 -400 {
lab=avdd}
N 1370 -320 1370 -280 {
lab=src_200_1}
N 1070 -360 1070 -300 {
lab=enb_200_1_3v3}
N 1440 -450 1440 -400 {
lab=pbias}
N 1410 -380 1440 -380 {
lab=pcasc}
N 1410 -470 1410 -380 {
lab=pcasc}
N 1740 -490 1740 -400 {
lab=avdd}
N 1740 -320 1740 -280 {
lab=src_200_2}
N 1440 -360 1440 -300 {
lab=enb_200_2_3v3}
N 1810 -450 1810 -400 {
lab=pbias}
N 1780 -380 1810 -380 {
lab=pcasc}
N 1780 -470 1780 -380 {
lab=pcasc}
N 2110 -490 2110 -400 {
lab=avdd}
N 2110 -320 2110 -280 {
lab=src_100}
N 1810 -360 1810 -300 {
lab=enb_100_3v3}
N 2180 -450 2180 -400 {
lab=pbias}
N 2150 -380 2180 -380 {
lab=pcasc}
N 2150 -470 2150 -380 {
lab=pcasc}
N 2480 -490 2480 -400 {
lab=avdd}
N 2480 -320 2480 -280 {
lab=src_50}
N 2180 -360 2180 -300 {
lab=enb_50_3v3}
N -550 -140 -550 -80 {
lab=nbias}
N -250 -120 -250 -60 {
lab=avss}
N -550 -210 -550 -160 {
lab=ena_4000_3v3}
N -250 -200 -250 -160 {
lab=snk_4000}
N -190 -140 -190 -80 {
lab=nbias}
N 110 -120 110 -60 {
lab=avss}
N -190 -210 -190 -160 {
lab=enb_2000_3v3}
N 110 -200 110 -160 {
lab=snk_2000}
N 990 -320 990 -290 {
lab=src_200_0}
N -920 -340 -900 -340 {
lab=avss}
N -900 -340 -900 -250 {
lab=avss}
N -940 -250 -900 -250 {
lab=avss}
N -940 -250 -940 -60 {
lab=avss}
N -550 -340 -530 -340 {
lab=avss}
N -530 -340 -530 -250 {
lab=avss}
N -570 -250 -530 -250 {
lab=avss}
N -570 -250 -570 -60 {
lab=avss}
N -170 -340 -150 -340 {
lab=avss}
N -150 -340 -150 -240 {
lab=avss}
N -210 -240 -150 -240 {
lab=avss}
N -210 -240 -210 -60 {
lab=avss}
N 220 -340 250 -340 {
lab=avss}
N 250 -340 250 -240 {
lab=avss}
N 140 -240 250 -240 {
lab=avss}
N 140 -240 140 -60 {
lab=avss}
N 610 -340 630 -340 {
lab=avss}
N 630 -340 630 -250 {
lab=avss}
N 490 -250 630 -250 {
lab=avss}
N 490 -250 490 -60 {
lab=avss}
N 990 -340 1020 -340 {
lab=avss}
N 1020 -340 1020 -60 {
lab=avss}
N 1370 -340 1400 -340 {
lab=avss}
N 1400 -340 1400 -60 {
lab=avss}
N 1740 -340 1770 -340 {
lab=avss}
N 1770 -340 1770 -60 {
lab=avss}
N 2110 -340 2140 -340 {
lab=avss}
N 2140 -340 2140 -60 {
lab=avss}
N 2480 -340 2500 -340 {
lab=avss}
N 2500 -340 2500 -60 {
lab=avss}
N -2460 -450 -2400 -450 {
lab=ena_snk_2000}
N -2320 -450 -2270 -450 {
lab=enb_2000_3v3}
N -2460 -400 -2400 -400 {
lab=ena_snk_4000}
N -2320 -400 -2270 -400 {
lab=ena_4000_3v3}
N -2460 -500 -2400 -500 {
lab=ena_snk_1000}
N -2320 -500 -2270 -500 {
lab=ena_1000_3v3}
N -2460 -350 -2400 -350 {
lab=ena_snk_5000}
N -2320 -350 -2270 -350 {
lab=ena_5000_3v3}
N -2460 -50 -2400 -50 {
lab=ena_snk_test1}
N -2320 -50 -2270 -50 {
lab=ena_test1_3v3}
N -1940 -550 -1880 -550 {
lab=ena_src_50}
N -1700 -550 -1650 -550 {
lab=enb_50_3v3}
N -1940 -500 -1880 -500 {
lab=ena_src_100}
N -1700 -500 -1650 -500 {
lab=enb_100_3v3}
N -1940 -450 -1880 -450 {
lab=ena_src_200_2}
N -1700 -450 -1650 -450 {
lab=enb_200_2_3v3}
N -1940 -400 -1880 -400 {
lab=ena_src_200_1}
N -1700 -400 -1650 -400 {
lab=enb_200_1_3v3}
N -1940 -350 -1880 -350 {
lab=ena_src_200_0}
N -1700 -350 -1650 -350 {
lab=enb_200_0_3v3}
N -1940 -300 -1880 -300 {
lab=ena_src_400}
N -1700 -300 -1650 -300 {
lab=enb_400_3v3}
N -1940 -250 -1880 -250 {
lab=ena_src_600}
N -1700 -250 -1650 -250 {
lab=enb_600_3v3}
N -1940 -150 -1880 -150 {
lab=ena_src_10000}
N -1700 -150 -1650 -150 {
lab=enb_10000_3v3}
N -1940 -200 -1880 -200 {
lab=ena_src_1000}
N -1700 -200 -1650 -200 {
lab=enb_1000_3v3}
N -1940 -50 -1880 -50 {
lab=ena_src_test1}
N -1700 -50 -1650 -50 {
lab=enb_test1_3v3}
N -1800 -50 -1780 -50 {
lab=#net1}
N -1800 -200 -1780 -200 {
lab=#net2}
N -1800 -150 -1780 -150 {
lab=#net3}
N -1800 -250 -1780 -250 {
lab=#net4}
N -1800 -300 -1780 -300 {
lab=#net5}
N -1800 -350 -1780 -350 {
lab=#net6}
N -1800 -400 -1780 -400 {
lab=#net7}
N -1800 -450 -1780 -450 {
lab=#net8}
N -1800 -500 -1780 -500 {
lab=#net9}
N -1800 -550 -1780 -550 {
lab=#net10}
N -1340 -700 -1300 -700 {
lab=dvdd}
N -1340 -670 -1300 -670 {
lab=dvss}
N -1260 -210 -1260 -160 {
lab=ena_test1_3v3}
N -1290 -140 -1260 -140 {
lab=nbias}
N -1290 -140 -1290 -80 {
lab=nbias}
N -1340 -490 -730 -490 {
lab=avdd}
N -1340 -470 -730 -470 {
lab=pcasc}
N -1340 -450 -730 -450 {
lab=pbias}
N -1330 -80 -720 -80 {
lab=nbias}
N -1330 -60 -720 -60 {
lab=avss}
N -730 -490 2480 -490 {
lab=avdd}
N -730 -470 2150 -470 {
lab=pcasc}
N -730 -450 2180 -450 {
lab=pbias}
N -720 -60 2500 -60 {
lab=avss}
N -720 -80 160 -80 {
lab=nbias}
N 510 -140 510 -80 {
lab=nbias}
N 810 -120 810 -60 {
lab=avss}
N 510 -210 510 -160 {
lab=ena_750_3v3}
N 810 -200 810 -160 {
lab=snk_750}
N 160 -80 510 -80 {
lab=nbias}
N -2460 -550 -2400 -550 {
lab=ena_snk_750}
N -2320 -550 -2270 -550 {
lab=ena_750_3v3}
C {devices/iopin.sym} -1330 -60 0 1 {name=p39 lab=avss}
C {devices/iopin.sym} -1340 -490 0 1 {name=p42 lab=avdd}
C {devices/lab_wire.sym} -1210 -80 0 0 {name=p43 sig_type=std_logic lab=nbias}
C {devices/lab_wire.sym} -1270 -450 0 0 {name=p44 sig_type=std_logic lab=pbias}
C {devices/lab_wire.sym} -1270 -470 0 0 {name=p45 sig_type=std_logic lab=pcasc}
C {bias_nstack.sym} -1110 -140 0 0 {name=x18[1:0]}
C {devices/ipin.sym} -2460 -50 0 0 {name=p50 lab=ena_snk_test1}
C {devices/iopin.sym} -960 -200 0 1 {name=p51 lab=snk_test1}
C {bias_pstack.sym} -1070 -360 0 0 {name=x16[1:0]}
C {devices/ipin.sym} -1940 -50 0 0 {name=p52 lab=ena_src_test1}
C {devices/iopin.sym} -920 -280 0 1 {name=p53 lab=src_test1}
C {bias_pstack.sym} -320 -360 0 0 {name=x8[19:0]}
C {devices/ipin.sym} -1940 -200 0 0 {name=p54 lab=ena_src_1000}
C {devices/iopin.sym} -170 -280 0 1 {name=p55 lab=src_1000}
C {bias_nstack.sym} -770 -140 0 0 {name=x9[99:0]}
C {devices/ipin.sym} -2460 -350 0 0 {name=p56 lab=ena_snk_5000}
C {devices/iopin.sym} -620 -200 0 1 {name=p57 lab=snk_5000}
C {bias_pstack.sym} -700 -360 0 0 {name=x10[199:0]}
C {devices/ipin.sym} -1940 -150 0 0 {name=p58 lab=ena_src_10000}
C {devices/iopin.sym} -550 -280 0 1 {name=p59 lab=src_10000}
C {bias_nstack.sym} 310 -140 0 0 {name=x1[19:0]}
C {devices/ipin.sym} -2460 -500 0 0 {name=p60 lab=ena_snk_1000}
C {devices/iopin.sym} 460 -200 0 1 {name=p61 lab=snk_1000}
C {bias_pstack.sym} 70 -360 0 0 {name=x4[11:0]}
C {devices/ipin.sym} -1940 -250 0 0 {name=p64 lab=ena_src_600}
C {devices/iopin.sym} 220 -280 0 1 {name=p65 lab=src_600}
C {bias_pstack.sym} 460 -360 0 0 {name=x5[7:0]}
C {devices/ipin.sym} -1940 -300 0 0 {name=p66 lab=ena_src_400}
C {devices/iopin.sym} 610 -280 0 1 {name=p67 lab=src_400}
C {bias_pstack.sym} 840 -360 0 0 {name=x6[3:0]}
C {devices/ipin.sym} -1940 -350 0 0 {name=p68 lab=ena_src_200_0}
C {devices/iopin.sym} 990 -290 0 1 {name=p69 lab=src_200_0}
C {bias_pstack.sym} 1220 -360 0 0 {name=x7[3:0]}
C {devices/ipin.sym} -1940 -400 0 0 {name=p70 lab=ena_src_200_1}
C {devices/iopin.sym} 1370 -280 0 1 {name=p71 lab=src_200_1}
C {bias_pstack.sym} 1590 -360 0 0 {name=x11[3:0]}
C {devices/ipin.sym} -1940 -450 0 0 {name=p72 lab=ena_src_200_2}
C {devices/iopin.sym} 1740 -280 0 1 {name=p73 lab=src_200_2}
C {bias_pstack.sym} 1960 -360 0 0 {name=x12[1:0]}
C {devices/ipin.sym} -1940 -500 0 0 {name=p74 lab=ena_src_100}
C {devices/iopin.sym} 2110 -280 0 1 {name=p75 lab=src_100}
C {bias_pstack.sym} 2330 -360 0 0 {name=x13}
C {devices/ipin.sym} -1940 -550 0 0 {name=p76 lab=ena_src_50}
C {devices/iopin.sym} 2480 -280 0 1 {name=p77 lab=src_50}
C {bias_nstack.sym} -400 -140 0 0 {name=x14[79:0]}
C {devices/ipin.sym} -2460 -400 0 0 {name=p78 lab=ena_snk_4000}
C {devices/iopin.sym} -250 -200 0 1 {name=p79 lab=snk_4000}
C {bias_nstack.sym} -40 -140 0 0 {name=x15[39:0]}
C {devices/ipin.sym} -2460 -450 0 0 {name=p80 lab=ena_snk_2000}
C {devices/iopin.sym} 110 -200 0 1 {name=p81 lab=snk_2000}
C {devices/lab_pin.sym} -1260 -210 0 1 {name=p10 sig_type=std_logic lab=ena_test1_3v3}
C {devices/lab_pin.sym} -1220 -300 0 1 {name=p11 sig_type=std_logic lab=enb_test1_3v3}
C {devices/lab_pin.sym} -920 -210 0 1 {name=p12 sig_type=std_logic lab=ena_5000_3v3}
C {devices/lab_pin.sym} -470 -300 0 1 {name=p13 sig_type=std_logic lab=enb_1000_3v3}
C {devices/lab_pin.sym} 160 -210 0 1 {name=p14 sig_type=std_logic lab=ena_1000_3v3}
C {devices/lab_pin.sym} -850 -300 0 1 {name=p16 sig_type=std_logic lab=enb_10000_3v3}
C {devices/lab_pin.sym} -80 -300 0 1 {name=p17 sig_type=std_logic lab=enb_600_3v3}
C {devices/lab_pin.sym} -550 -210 0 1 {name=p18 sig_type=std_logic lab=ena_4000_3v3}
C {devices/lab_pin.sym} 310 -300 0 1 {name=p19 sig_type=std_logic lab=enb_400_3v3}
C {devices/lab_pin.sym} -190 -210 0 1 {name=p20 sig_type=std_logic lab=enb_2000_3v3}
C {devices/lab_pin.sym} 690 -300 0 1 {name=p21 sig_type=std_logic lab=enb_200_0_3v3}
C {devices/lab_pin.sym} 1070 -300 0 1 {name=p22 sig_type=std_logic lab=enb_200_1_3v3}
C {devices/lab_pin.sym} 1440 -300 0 1 {name=p23 sig_type=std_logic lab=enb_200_2_3v3}
C {devices/lab_pin.sym} 1810 -300 0 1 {name=p24 sig_type=std_logic lab=enb_100_3v3}
C {devices/lab_pin.sym} 2180 -300 0 1 {name=p25 sig_type=std_logic lab=enb_50_3v3}
C {lsbuflv2hv_1.sym} -2360 -450 0 0 {name=x5 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {lsbuflv2hv_1.sym} -2360 -400 0 0 {name=x6 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {lsbuflv2hv_1.sym} -2360 -500 0 0 {name=x8 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {lsbuflv2hv_1.sym} -2360 -350 0 0 {name=x9 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {lsbuflv2hv_1.sym} -2360 -50 0 0 {name=x10 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {lsbuflv2hv_1.sym} -1840 -550 0 0 {name=x12 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -500 0 0 {name=x14 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -450 0 0 {name=x15 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -400 0 0 {name=x16 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -350 0 0 {name=x17 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -300 0 0 {name=x18 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -250 0 0 {name=x19 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -150 0 0 {name=x20 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -200 0 0 {name=x21 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -50 0 0 {name=x22 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {devices/lab_pin.sym} -2270 -50 0 1 {name=p28 sig_type=std_logic lab=ena_test1_3v3}
C {devices/lab_pin.sym} -1650 -50 0 1 {name=p29 sig_type=std_logic lab=enb_test1_3v3}
C {devices/lab_pin.sym} -2270 -350 0 1 {name=p30 sig_type=std_logic lab=ena_5000_3v3}
C {devices/lab_pin.sym} -1650 -200 0 1 {name=p31 sig_type=std_logic lab=enb_1000_3v3}
C {devices/lab_pin.sym} -2270 -500 0 1 {name=p32 sig_type=std_logic lab=ena_1000_3v3}
C {devices/lab_pin.sym} -1650 -150 0 1 {name=p34 sig_type=std_logic lab=enb_10000_3v3}
C {devices/lab_pin.sym} -1650 -250 0 1 {name=p35 sig_type=std_logic lab=enb_600_3v3}
C {devices/lab_pin.sym} -2270 -400 0 1 {name=p36 sig_type=std_logic lab=ena_4000_3v3}
C {devices/lab_pin.sym} -1650 -300 0 1 {name=p37 sig_type=std_logic lab=enb_400_3v3}
C {devices/lab_pin.sym} -2270 -450 0 1 {name=p41 sig_type=std_logic lab=enb_2000_3v3}
C {devices/lab_pin.sym} -1650 -350 0 1 {name=p82 sig_type=std_logic lab=enb_200_0_3v3}
C {devices/lab_pin.sym} -1650 -400 0 1 {name=p83 sig_type=std_logic lab=enb_200_1_3v3}
C {devices/lab_pin.sym} -1650 -450 0 1 {name=p84 sig_type=std_logic lab=enb_200_2_3v3}
C {devices/lab_pin.sym} -1650 -500 0 1 {name=p85 sig_type=std_logic lab=enb_100_3v3}
C {devices/lab_pin.sym} -1650 -550 0 1 {name=p86 sig_type=std_logic lab=enb_50_3v3}
C {sky130_stdcells/inv_2.sym} -1740 -550 0 0 {name=x25 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -500 0 0 {name=x26 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -450 0 0 {name=x27 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -400 0 0 {name=x28 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -350 0 0 {name=x29 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -300 0 0 {name=x30 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -250 0 0 {name=x31 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -150 0 0 {name=x32 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -200 0 0 {name=x33 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -50 0 0 {name=x34 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {devices/noconn.sym} -920 -360 0 1 {name=l4}
C {devices/noconn.sym} -960 -140 0 1 {name=l5}
C {devices/noconn.sym} -620 -140 0 1 {name=l6}
C {devices/noconn.sym} -550 -360 0 1 {name=l7}
C {devices/noconn.sym} 460 -140 0 1 {name=l8}
C {devices/noconn.sym} -170 -360 0 1 {name=l9}
C {devices/noconn.sym} 220 -360 0 1 {name=l10}
C {devices/noconn.sym} -250 -140 0 1 {name=l12}
C {devices/noconn.sym} 610 -360 0 1 {name=l13}
C {devices/noconn.sym} 110 -140 0 1 {name=l14}
C {devices/noconn.sym} 990 -360 0 1 {name=l15}
C {devices/noconn.sym} 1370 -360 0 1 {name=l16}
C {devices/noconn.sym} 1740 -360 0 1 {name=l17}
C {devices/noconn.sym} 2110 -360 0 1 {name=l18}
C {devices/noconn.sym} 2480 -360 0 1 {name=l19}
C {devices/iopin.sym} -1340 -700 0 1 {name=p98 lab=dvdd}
C {devices/iopin.sym} -1340 -670 0 1 {name=p99 lab=dvss}
C {devices/lab_pin.sym} -1300 -700 0 1 {name=p1 sig_type=std_logic lab=dvdd}
C {devices/lab_pin.sym} -1300 -670 0 1 {name=p2 sig_type=std_logic lab=dvss}
C {devices/lab_pin.sym} 1940 -2300 0 0 {name=p109 sig_type=std_logic lab=vbg}
C {devices/ipin.sym} -1340 -470 0 0 {name=p3 lab=pcasc}
C {devices/ipin.sym} -1340 -450 0 0 {name=p4 lab=pbias}
C {devices/ipin.sym} -1330 -80 0 0 {name=p5 lab=nbias}
C {bias_nstack.sym} 660 -140 0 0 {name=x2[14:0]}
C {devices/iopin.sym} 810 -200 0 1 {name=p6 lab=snk_750}
C {devices/lab_pin.sym} 510 -210 0 1 {name=p7 sig_type=std_logic lab=ena_750_3v3}
C {devices/noconn.sym} 810 -140 0 1 {name=l1}
C {devices/ipin.sym} -2460 -550 0 0 {name=p8 lab=ena_snk_750}
C {lsbuflv2hv_1.sym} -2360 -550 0 0 {name=x1 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {devices/lab_pin.sym} -2270 -550 0 1 {name=p9 sig_type=std_logic lab=ena_750_3v3}
C {sky130_stdcells/decap_4.sym} -2350 -210 0 0 {name=x3[5:0] VGND=dvdd VNB=dvdd VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
