v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
T {Each bias_nstack is a 50nA unit current sink, and each bias_pstack is a 50nA unit current source.
Any bias current back-end can be generated by chaining together unit sources and/or sinks.} -1360 -630 0 0 0.4 0.4 {}
T {dummy} -1110 -30 0 0 0.4 0.4 {}
T {50nA} -710 -540 0 0 0.4 0.4 {}
T {Level shifters (1.8V to 3.3V)} -2140 -660 0 0 0.4 0.4 {}
T {Bias generator back-end} -2190 -780 0 0 0.6 0.6 {}
T {dummy} -1110 -530 0 0 0.4 0.4 {}
T {100nA} -190 -540 0 0 0.4 0.4 {}
T {200nA} 210 -540 0 0 0.4 0.4 {}
T {400nA} 570 -540 0 0 0.4 0.4 {}
T {800nA} 960 -540 0 0 0.4 0.4 {}
T {1.6uA} 1320 -540 0 0 0.4 0.4 {}
T {3.2uA} 1690 -540 0 0 0.4 0.4 {}
T {6.4uA} 2050 -540 0 0 0.4 0.4 {}
N -950 -120 -950 -60 {
lab=avss}
N -1210 -450 -1210 -400 {
lab=pbias}
N -1240 -380 -1210 -380 {
lab=pcasc}
N -910 -490 -910 -400 {
lab=avdd}
N -840 -450 -840 -400 {
lab=pbias}
N -870 -380 -840 -380 {
lab=pcasc}
N -870 -470 -870 -380 {
lab=pcasc}
N -540 -490 -540 -400 {
lab=avdd}
N -540 -320 -540 -280 {
lab=src_out}
N -840 -360 -840 -300 {
lab=enb_bit0}
N -300 -450 -300 -400 {
lab=pbias}
N -330 -380 -300 -380 {
lab=pcasc}
N -330 -470 -330 -380 {
lab=pcasc}
N 0 -490 0 -400 {
lab=avdd}
N 0 -320 0 -280 {
lab=src_out}
N -300 -360 -300 -300 {
lab=enb_bit1}
N -440 -490 480 -490 {
lab=avdd}
N -440 -470 480 -470 {
lab=pcasc}
N -440 -450 480 -450 {
lab=pbias}
N 90 -450 90 -400 {
lab=pbias}
N 60 -380 90 -380 {
lab=pcasc}
N 60 -470 60 -380 {
lab=pcasc}
N 390 -490 390 -400 {
lab=avdd}
N 390 -320 390 -280 {
lab=src_out}
N 90 -360 90 -300 {
lab=enb_bit2}
N 470 -450 470 -400 {
lab=pbias}
N 440 -380 470 -380 {
lab=pcasc}
N 440 -470 440 -380 {
lab=pcasc}
N 770 -490 770 -400 {
lab=avdd}
N 470 -360 470 -300 {
lab=enb_bit3}
N 480 -450 1400 -450 {
lab=pbias}
N 480 -470 1390 -470 {
lab=pcasc}
N 480 -490 1390 -490 {
lab=avdd}
N 850 -450 850 -400 {
lab=pbias}
N 820 -380 850 -380 {
lab=pcasc}
N 820 -470 820 -380 {
lab=pcasc}
N 1150 -490 1150 -400 {
lab=avdd}
N 1150 -320 1150 -280 {
lab=src_out}
N 850 -360 850 -300 {
lab=enb_bit4}
N 1220 -450 1220 -400 {
lab=pbias}
N 1190 -380 1220 -380 {
lab=pcasc}
N 1190 -470 1190 -380 {
lab=pcasc}
N 1520 -490 1520 -400 {
lab=avdd}
N 1520 -320 1520 -280 {
lab=src_out}
N 1220 -360 1220 -300 {
lab=enb_bit5}
N 1390 -490 2140 -490 {
lab=avdd}
N 1590 -450 1590 -400 {
lab=pbias}
N 1560 -380 1590 -380 {
lab=pcasc}
N 1560 -470 1560 -380 {
lab=pcasc}
N 1890 -490 1890 -400 {
lab=avdd}
N 1890 -320 1890 -280 {
lab=src_out}
N 1590 -360 1590 -300 {
lab=enb_bit6}
N 1960 -450 1960 -400 {
lab=pbias}
N 1930 -380 1960 -380 {
lab=pcasc}
N 1930 -470 1930 -380 {
lab=pcasc}
N 2260 -490 2260 -400 {
lab=avdd}
N 2260 -320 2260 -280 {
lab=src_out}
N 1960 -360 1960 -300 {
lab=enb_bit7}
N 2140 -490 2260 -490 {
lab=avdd}
N 1390 -470 1930 -470 {
lab=pcasc}
N 1400 -450 1960 -450 {
lab=pbias}
N -910 -340 -890 -340 {
lab=avss}
N -540 -340 -520 -340 {
lab=avss}
N -520 -340 -520 -250 {
lab=avss}
N -520 -250 -520 -60 {
lab=avss}
N 0 -340 30 -340 {
lab=avss}
N 390 -340 410 -340 {
lab=avss}
N 770 -340 800 -340 {
lab=avss}
N 800 -340 800 -60 {
lab=avss}
N 1150 -340 1180 -340 {
lab=avss}
N 1180 -340 1180 -60 {
lab=avss}
N 1520 -340 1550 -340 {
lab=avss}
N 1550 -340 1550 -60 {
lab=avss}
N 1890 -340 1920 -340 {
lab=avss}
N 1920 -340 1920 -60 {
lab=avss}
N 2260 -340 2280 -340 {
lab=avss}
N 2280 -340 2280 -60 {
lab=avss}
N -1940 -550 -1880 -550 {
lab=ena[0]}
N -1700 -550 -1650 -550 {
lab=enb_bit0}
N -1940 -480 -1880 -480 {
lab=ena[1]}
N -1700 -480 -1650 -480 {
lab=enb_bit1}
N -1940 -410 -1880 -410 {
lab=ena[2]}
N -1700 -410 -1650 -410 {
lab=enb_bit2}
N -1940 -340 -1880 -340 {
lab=ena[3]}
N -1700 -340 -1650 -340 {
lab=enb_bit3}
N -1940 -270 -1880 -270 {
lab=ena[4]}
N -1700 -270 -1650 -270 {
lab=enb_bit4}
N -1940 -200 -1880 -200 {
lab=ena[5]}
N -1700 -200 -1650 -200 {
lab=enb_bit5}
N -1940 -130 -1880 -130 {
lab=ena[6]}
N -1700 -130 -1650 -130 {
lab=enb_bit6}
N -1940 -60 -1880 -60 {
lab=ena[7]}
N -1700 -60 -1650 -60 {
lab=enb_bit7}
N -1800 -60 -1780 -60 {
lab=ena_bit7}
N -1800 -130 -1780 -130 {
lab=ena_bit6}
N -1800 -200 -1780 -200 {
lab=ena_bit5}
N -1800 -270 -1780 -270 {
lab=ena_bit4}
N -1800 -340 -1780 -340 {
lab=ena_bit3}
N -1800 -410 -1780 -410 {
lab=ena_bit2}
N -1800 -480 -1780 -480 {
lab=ena_bit1}
N -1800 -550 -1780 -550 {
lab=ena_bit0}
N -1340 -700 -1300 -700 {
lab=dvdd}
N -1340 -670 -1300 -670 {
lab=dvss}
N -1340 -470 -440 -470 {
lab=pcasc}
N -1340 -450 -1270 -450 {
lab=pbias}
N -1340 -490 -440 -490 {
lab=avdd}
N -1330 -60 -430 -60 {
lab=avss}
N -1240 -470 -1240 -380 {
lab=pcasc}
N -1270 -450 -440 -450 {
lab=pbias}
N -430 -60 2280 -60 {
lab=avss}
N -540 -120 -540 -60 {
lab=avss}
N -540 -200 -540 -160 {
lab=snk_out}
N -840 -140 -840 -80 {
lab=nbias}
N -1250 -140 -1250 -80 {
lab=nbias}
N -1340 -80 -1250 -80 {
lab=nbias}
N -1250 -80 -330 -80 {
lab=nbias}
N -890 -340 -890 -60 {
lab=avss}
N -1260 -360 -1210 -360 {
lab=avdd}
N -1260 -490 -1260 -360 {
lab=avdd}
N -1270 -160 -1250 -160 {
lab=avss}
N -1270 -160 -1270 -60 {
lab=avss}
N 410 -340 410 -60 {
lab=avss}
N 30 -340 30 -60 {
lab=avss}
N -330 -280 2260 -280 {
lab=src_out}
N -540 -280 -330 -280 {
lab=src_out}
N -30 -120 -30 -60 {
lab=avss}
N -30 -200 -30 -160 {
lab=snk_out}
N -330 -140 -330 -80 {
lab=nbias}
N -330 -240 -330 -160 {
lab=ena_bit1}
N 770 -320 770 -280 {
lab=src_out}
N 350 -120 350 -60 {
lab=avss}
N 350 -200 350 -160 {
lab=snk_out}
N 50 -140 50 -80 {
lab=nbias}
N 50 -240 50 -160 {
lab=ena_bit2}
N 730 -120 730 -60 {
lab=avss}
N 730 -200 730 -160 {
lab=snk_out}
N 430 -140 430 -80 {
lab=nbias}
N 430 -240 430 -160 {
lab=ena_bit3}
N 1120 -120 1120 -60 {
lab=avss}
N 1120 -200 1120 -160 {
lab=snk_out}
N 820 -140 820 -80 {
lab=nbias}
N 820 -240 820 -160 {
lab=ena_bit4}
N 1500 -120 1500 -60 {
lab=avss}
N 1500 -200 1500 -160 {
lab=snk_out}
N 1200 -140 1200 -80 {
lab=nbias}
N 1200 -240 1200 -160 {
lab=ena_bit5}
N 1870 -120 1870 -60 {
lab=avss}
N 1870 -200 1870 -160 {
lab=snk_out}
N 1570 -140 1570 -80 {
lab=nbias}
N 1570 -240 1570 -160 {
lab=ena_bit6}
N 2240 -120 2240 -60 {
lab=avss}
N 2240 -200 2240 -160 {
lab=snk_out}
N 1940 -140 1940 -80 {
lab=nbias}
N 1940 -240 1940 -160 {
lab=ena_bit7}
N -540 -200 2240 -200 {
lab=snk_out}
N -330 -80 1940 -80 {
lab=nbias}
N -1780 -590 -1780 -550 {
lab=ena_bit0}
N -1780 -590 -1650 -590 {
lab=ena_bit0}
N -1780 -520 -1780 -480 {
lab=ena_bit1}
N -1780 -520 -1650 -520 {
lab=ena_bit1}
N -1780 -450 -1780 -410 {
lab=ena_bit2}
N -1780 -450 -1650 -450 {
lab=ena_bit2}
N -1780 -380 -1780 -340 {
lab=ena_bit3}
N -1780 -380 -1650 -380 {
lab=ena_bit3}
N -1780 -310 -1780 -270 {
lab=ena_bit4}
N -1780 -310 -1650 -310 {
lab=ena_bit4}
N -1780 -240 -1780 -200 {
lab=ena_bit5}
N -1780 -240 -1650 -240 {
lab=ena_bit5}
N -1780 -170 -1780 -130 {
lab=ena_bit6}
N -1780 -170 -1650 -170 {
lab=ena_bit6}
N -1780 -100 -1780 -60 {
lab=ena_bit7}
N -1780 -100 -1650 -100 {
lab=ena_bit7}
N -950 -200 -540 -200 {
lab=snk_out}
N -950 -280 -540 -280 {
lab=src_out}
N -840 -240 -840 -160 {
lab=ena_bit0}
N -950 -200 -950 -160 {
lab=snk_out}
N -910 -320 -910 -280 {
lab=src_out}
N -1680 40 -1650 40 {
lab=ena[0]}
N -1680 80 -1650 80 {
lab=ena[1]}
N -1680 160 -1650 160 {
lab=ena[3]}
N -1680 120 -1650 120 {
lab=ena[2]}
N -1320 40 -1290 40 {
lab=ena[4]}
N -1320 80 -1290 80 {
lab=ena[5]}
N -1320 160 -1290 160 {
lab=ena[7]}
N -1320 120 -1290 120 {
lab=ena[6]}
C {devices/iopin.sym} -1330 -60 0 1 {name=p39 lab=avss}
C {devices/iopin.sym} -1340 -490 0 1 {name=p42 lab=avdd}
C {bias_nstack.sym} -1100 -140 0 0 {name=x3}
C {bias_pstack.sym} -1060 -360 0 0 {name=x1}
C {bias_pstack.sym} -690 -360 0 0 {name=x8}
C {devices/iopin.sym} -950 -280 0 1 {name=p55 lab=src_out}
C {bias_pstack.sym} -150 -360 0 0 {name=x4[1:0]}
C {bias_pstack.sym} 240 -360 0 0 {name=x5[3:0]}
C {bias_pstack.sym} 620 -360 0 0 {name=x6[7:0]}
C {bias_pstack.sym} 1000 -360 0 0 {name=x7[15:0]}
C {bias_pstack.sym} 1370 -360 0 0 {name=x11[31:0]}
C {bias_pstack.sym} 1740 -360 0 0 {name=x12[63:0]}
C {bias_pstack.sym} 2110 -360 0 0 {name=x1[127:0]}
C {devices/ipin.sym} -2080 -560 0 0 {name=p76 lab=ena[7:0]}
C {devices/lab_pin.sym} -840 -300 0 1 {name=p13 sig_type=std_logic lab=enb_bit0}
C {devices/lab_pin.sym} -300 -300 0 1 {name=p17 sig_type=std_logic lab=enb_bit1}
C {devices/lab_pin.sym} 90 -300 0 1 {name=p19 sig_type=std_logic lab=enb_bit2}
C {devices/lab_pin.sym} 470 -300 0 1 {name=p21 sig_type=std_logic lab=enb_bit3}
C {devices/lab_pin.sym} 850 -300 0 1 {name=p22 sig_type=std_logic lab=enb_bit4}
C {devices/lab_pin.sym} 1220 -300 0 1 {name=p23 sig_type=std_logic lab=enb_bit5}
C {devices/lab_pin.sym} 1590 -300 0 1 {name=p24 sig_type=std_logic lab=enb_bit6}
C {devices/lab_pin.sym} 1960 -300 0 1 {name=p25 sig_type=std_logic lab=enb_bit7}
C {lsbuflv2hv_1.sym} -1840 -550 0 0 {name=x12 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -480 0 0 {name=x14 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -410 0 0 {name=x15 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -340 0 0 {name=x16 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -270 0 0 {name=x17 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -200 0 0 {name=x18 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -130 0 0 {name=x19 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {lsbuflv2hv_1.sym} -1840 -60 0 0 {name=x20 LVPWR=dvdd VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ lab=enb}
C {devices/lab_pin.sym} -1650 -60 0 1 {name=p34 sig_type=std_logic lab=enb_bit7}
C {devices/lab_pin.sym} -1650 -130 0 1 {name=p35 sig_type=std_logic lab=enb_bit6}
C {devices/lab_pin.sym} -1650 -200 0 1 {name=p37 sig_type=std_logic lab=enb_bit5}
C {devices/lab_pin.sym} -1650 -270 0 1 {name=p82 sig_type=std_logic lab=enb_bit4}
C {devices/lab_pin.sym} -1650 -340 0 1 {name=p83 sig_type=std_logic lab=enb_bit3}
C {devices/lab_pin.sym} -1650 -410 0 1 {name=p84 sig_type=std_logic lab=enb_bit2}
C {devices/lab_pin.sym} -1650 -480 0 1 {name=p85 sig_type=std_logic lab=enb_bit1}
C {devices/lab_pin.sym} -1650 -550 0 1 {name=p86 sig_type=std_logic lab=enb_bit0}
C {sky130_stdcells/inv_2.sym} -1740 -550 0 0 {name=x25 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -480 0 0 {name=x26 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -410 0 0 {name=x27 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -340 0 0 {name=x28 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -270 0 0 {name=x29 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -200 0 0 {name=x30 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -130 0 0 {name=x31 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/inv_2.sym} -1740 -60 0 0 {name=x32 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {devices/noconn.sym} -910 -360 0 1 {name=l4}
C {devices/noconn.sym} -950 -140 0 1 {name=l5}
C {devices/noconn.sym} -540 -360 0 1 {name=l7}
C {devices/noconn.sym} 0 -360 0 1 {name=l10[1:0]}
C {devices/noconn.sym} 390 -360 0 1 {name=l13[3:0]}
C {devices/noconn.sym} 770 -360 0 1 {name=l15[7:0]}
C {devices/noconn.sym} 1150 -360 0 1 {name=l16[15:0]}
C {devices/noconn.sym} 1520 -360 0 1 {name=l17[31:0]}
C {devices/noconn.sym} 1890 -360 0 1 {name=l18[63:0]}
C {devices/noconn.sym} 2260 -360 0 1 {name=l19[127:0]}
C {devices/iopin.sym} -1340 -700 0 1 {name=p98 lab=dvdd}
C {devices/iopin.sym} -1340 -670 0 1 {name=p99 lab=dvss}
C {devices/lab_pin.sym} -1300 -700 0 1 {name=p1 sig_type=std_logic lab=dvdd}
C {devices/lab_pin.sym} -1300 -670 0 1 {name=p2 sig_type=std_logic lab=dvss}
C {devices/ipin.sym} -1340 -470 0 0 {name=p3 lab=pcasc}
C {devices/ipin.sym} -1340 -450 0 0 {name=p4 lab=pbias}
C {devices/ipin.sym} -1340 -80 0 0 {name=p5 lab=nbias}
C {bias_nstack.sym} -690 -140 0 0 {name=x2}
C {devices/iopin.sym} -950 -200 0 1 {name=p7 lab=snk_out}
C {devices/noconn.sym} -540 -140 0 1 {name=l1}
C {devices/lab_pin.sym} -840 -240 0 1 {name=p9 sig_type=std_logic lab=ena_bit0}
C {devices/lab_pin.sym} -330 -240 0 1 {name=p6 sig_type=std_logic lab=ena_bit1}
C {bias_nstack.sym} -180 -140 0 0 {name=x2[1:0]}
C {devices/noconn.sym} -30 -140 0 1 {name=l6[1:0]}
C {devices/lab_pin.sym} 50 -240 0 1 {name=p11 sig_type=std_logic lab=ena_bit2}
C {bias_nstack.sym} 200 -140 0 0 {name=x3[3:0]}
C {devices/noconn.sym} 350 -140 0 1 {name=l8[3:0]}
C {devices/lab_pin.sym} 430 -240 0 1 {name=p12 sig_type=std_logic lab=ena_bit3}
C {bias_nstack.sym} 580 -140 0 0 {name=x9[7:0]}
C {devices/noconn.sym} 730 -140 0 1 {name=l9[7:0]}
C {devices/lab_pin.sym} 820 -240 0 1 {name=p14 sig_type=std_logic lab=ena_bit4}
C {bias_nstack.sym} 970 -140 0 0 {name=x10[15:0]}
C {devices/noconn.sym} 1120 -140 0 1 {name=l11[15:0]}
C {devices/lab_pin.sym} 1200 -240 0 1 {name=p15 sig_type=std_logic lab=ena_bit5}
C {bias_nstack.sym} 1350 -140 0 0 {name=x13[31:0]}
C {devices/noconn.sym} 1500 -140 0 1 {name=l12[31:0]}
C {devices/lab_pin.sym} 1570 -240 0 1 {name=p16 sig_type=std_logic lab=ena_bit6}
C {bias_nstack.sym} 1720 -140 0 0 {name=x14[63:0]}
C {devices/noconn.sym} 1870 -140 0 1 {name=l14[63:0]}
C {devices/lab_pin.sym} 1940 -240 0 1 {name=p18 sig_type=std_logic lab=ena_bit7}
C {bias_nstack.sym} 2090 -140 0 0 {name=x15[127:0]}
C {devices/noconn.sym} 2240 -140 0 1 {name=l20[127:0]}
C {devices/lab_pin.sym} -1650 -590 0 1 {name=p8 sig_type=std_logic lab=ena_bit0}
C {devices/lab_pin.sym} -1650 -520 0 1 {name=p10 sig_type=std_logic lab=ena_bit1}
C {devices/lab_pin.sym} -1650 -450 0 1 {name=p20 sig_type=std_logic lab=ena_bit2}
C {devices/lab_pin.sym} -1650 -380 0 1 {name=p26 sig_type=std_logic lab=ena_bit3}
C {devices/lab_pin.sym} -1650 -310 0 1 {name=p27 sig_type=std_logic lab=ena_bit4}
C {devices/lab_pin.sym} -1650 -240 0 1 {name=p28 sig_type=std_logic lab=ena_bit5}
C {devices/lab_pin.sym} -1650 -170 0 1 {name=p29 sig_type=std_logic lab=ena_bit6}
C {devices/lab_pin.sym} -1650 -100 0 1 {name=p30 sig_type=std_logic lab=ena_bit7}
C {devices/lab_pin.sym} -1940 -550 0 0 {name=p31 sig_type=std_logic lab=ena[0]}
C {devices/lab_pin.sym} -1940 -480 0 0 {name=p32 sig_type=std_logic lab=ena[1]}
C {devices/lab_pin.sym} -1940 -410 0 0 {name=p33 sig_type=std_logic lab=ena[2]}
C {devices/lab_pin.sym} -1940 -340 0 0 {name=p36 sig_type=std_logic lab=ena[3]}
C {devices/lab_pin.sym} -1940 -270 0 0 {name=p38 sig_type=std_logic lab=ena[4]}
C {devices/lab_pin.sym} -1940 -200 0 0 {name=p40 sig_type=std_logic lab=ena[5]}
C {devices/lab_pin.sym} -1940 -130 0 0 {name=p41 sig_type=std_logic lab=ena[6]}
C {devices/lab_pin.sym} -1940 -60 0 0 {name=p43 sig_type=std_logic lab=ena[7]}
C {sky130_stdcells/decap_4.sym} -1890 40 0 0 {name=x8[7:0] VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/diode_2.sym} -1560 40 0 0 {name=x4 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {devices/lab_pin.sym} -1680 40 0 0 {name=p46 sig_type=std_logic lab=ena[0]}
C {devices/lab_pin.sym} -1680 80 0 0 {name=p47 sig_type=std_logic lab=ena[1]}
C {devices/lab_pin.sym} -1680 120 0 0 {name=p48 sig_type=std_logic lab=ena[2]}
C {devices/lab_pin.sym} -1680 160 0 0 {name=p49 sig_type=std_logic lab=ena[3]}
C {devices/lab_pin.sym} -1320 40 0 0 {name=p50 sig_type=std_logic lab=ena[4]}
C {devices/lab_pin.sym} -1320 80 0 0 {name=p51 sig_type=std_logic lab=ena[5]}
C {devices/lab_pin.sym} -1320 120 0 0 {name=p52 sig_type=std_logic lab=ena[6]}
C {devices/lab_pin.sym} -1320 160 0 0 {name=p53 sig_type=std_logic lab=ena[7]}
C {sky130_stdcells/diode_2.sym} -1560 80 0 0 {name=x5 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/diode_2.sym} -1560 120 0 0 {name=x6 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/diode_2.sym} -1560 160 0 0 {name=x7 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/diode_2.sym} -1200 40 0 0 {name=x9 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/diode_2.sym} -1200 80 0 0 {name=x10 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/diode_2.sym} -1200 120 0 0 {name=x11 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
C {sky130_stdcells/diode_2.sym} -1200 160 0 0 {name=x13 VGND=dvss VNB=dvss VPB=avdd VPWR=avdd prefix=sky130_fd_sc_hvl__ }
